# This workflow is used for testing the aws-gov terraform module.

name: AWS Gov Tests
on:
  push:
    paths:
      - 'aws-gov/tf/**'
      - '.github/workflows/aws-gov-test.yml'
  pull_request:
    paths:
      - 'aws-gov/tf/**'
      - '.github/workflows/aws-gov-test.yml'
jobs:
  test-azure:
    uses: ./.github/workflows/terraform-ruw.yml
    with:
      working_directory: aws-gov/tf
      tflint_args: "--config=$(pwd)/.tflint.hcl"
