# This workflow is used for testing the Azure terraform module.

name: Azure Tests
on:
  push:
    paths:
      - 'azure/tf/**'
      - '.github/workflows/azure-test.yml'
  pull_request:
    paths:
      - 'azure/tf/**'
      - '.github/workflows/azure-test.yml'
jobs:
  test-azure:
    uses: ./.github/workflows/terraform-ruw.yml
    with:
      working_directory: azure/tf
      terraform_fmt_check: true
      terraform_test_args: "-filter=tests/mock_plan.tftest.hcl"
